services:
  it-tools:
    image: 'corentinth/it-tools:latest'
    restart: unless-stopped
    container_name: it-tools
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.it-tools.entrypoints=websecure"
      - "traefik.http.routers.it-tools.rule=Host(`it-tools.${DOMAIN_NAME}`)"
      - "traefik.http.routers.it-tools.tls=true"
      - "traefik.http.routers.it-tools.tls.certresolver=cloudflare"
      - "traefik.http.routers.it-tools.service=it-tools"
      - "traefik.http.routers.it-tools.middlewares=local-only@file,authentik@file,security-headers@file"
      - "traefik.http.services.it-tools.loadbalancer.server.port=80"

networks:
  homelab:
    external: true
