services:
  postgres:
    image: postgres:16-alpine
    env_file: .env
    restart: unless-stopped
    networks:
      - linkwarden
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  linkwarden:
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: unless-stopped
    image: ghcr.io/linkwarden/linkwarden:latest # comment to build from source
    networks:
      - linkwarden
      - homelab
    volumes:
      - ./data:/data/data
    depends_on:
      - postgres
      - meilisearch
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.linkwarden.entrypoints=websecure"
      - "traefik.http.routers.linkwarden.rule=Host(`linkwarden.${DOMAIN_NAME}`)"
      - "traefik.http.routers.linkwarden.tls=true"
      - "traefik.http.routers.linkwarden.tls.certresolver=cloudflare"
      - "traefik.http.routers.linkwarden.service=linkwarden"
      - "traefik.http.routers.linkwarden.middlewares=local-only@file,authentik@file,security-headers@file"
      - "traefik.http.services.linkwarden.loadbalancer.server.port=3000"
  meilisearch:
    image: getmeili/meilisearch:v1.12.8
    restart: unless-stopped
    networks:
      - linkwarden
    env_file:
      - .env
    volumes:
      - ./meili_data:/meili_data

networks:
  linkwarden:
    name: linkwarden
  homelab:
    name: homelab
    external: true
