services:
  bentopdf:
    image: bentopdf/bentopdf:latest
    container_name: bentopdf
    security_opt:
      - no-new-privileges:true
    networks:
      - homelab
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bentopdf.entrypoints=websecure"
      - "traefik.http.routers.bentopdf.rule=Host(`bentopdf.${DOMAIN_NAME}`)"
      - "traefik.http.routers.bentopdf.tls=true"
      - "traefik.http.routers.bentopdf.tls.certresolver=cloudflare"
      - "traefik.http.routers.bentopdf.service=bentopdf"
      - "traefik.http.routers.bentopdf.middlewares=local-only@file,authentik@file,security-headers@file"
      - "traefik.http.services.bentopdf.loadbalancer.server.port=8080"
networks:
  homelab:
    name: homelab
    external: true
