services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    user: "65534:65534"
    security_opt:
      - no-new-privileges:true
    networks:
      - homelab
      - monitoring
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PSWD}
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN_NAME}`)"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=cloudflare"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.routers.grafana.middlewares=local-only@file,authentik@file,security-headers@file"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

#  k6:
#    build: .
#    container_name: k6
#    env_file:
#      - .env
#    networks:
#      - monitoring
#    security_opt:
#      - no-new-privileges:true
#    volumes:
#      - ./scripts:/scripts
#      - ./results:/results
#    working_dir: /scripts
#    environment:
#      - K6_BROWSER_ENABLED=true
#      - K6_INFLUXDB_ORGANIZATION=${K6_INFLUXDB_ORGANIZATION}
#      - K6_INFLUXDB_BUCKET=${K6_INFLUXDB_BUCKET}
#      - K6_INFLUXDB_TOKEN=${K6_INFLUXDB_TOKEN}
#  pw:
#    build:
#      context: .
#      dockerfile: Dockerfile.playwright
#    container_name: pw
#    env_file:
#      - .env
#    working_dir: /scripts
#    networks:
#      - monitoring
#    security_opt:
#      - no-new-privileges:true
#    volumes:
#      - ./scripts:/scripts
#      - ./results:/results
#    environment:
#      - INFLUX_URL=${K6_INFLUXDB_URL:-http://influxdb:8086}
#      - INFLUX_ORG=${K6_INFLUXDB_ORGANIZATION}
#      - INFLUX_BUCKET=${K6_INFLUXDB_BUCKET}
#      - INFLUX_TOKEN=${K6_INFLUXDB_TOKEN}
 # loki:
 #   image: grafana/loki:latest
 #   container_name: loki
 #   command: -config.file=/etc/loki/local-config.yaml
 #   restart: unless-stopped
 #   user: "10001:10001"
 #   security_opt:
 #     - no-new-privileges:true
 #   networks:
 #     - grafana-monitoring
 #     - homelab
 #   volumes:
 #     - ./loki_config/config.yaml:/etc/loki/config.yaml:ro
 #     - ./loki_data:/loki:rw
 #   labels:
 #     - "traefik.enable=true"
 #     - "traefik.http.routers.loki.entrypoints=websecure"
 #     - "traefik.http.routers.loki.rule=Host(`loki.${DOMAIN_NAME}`)"
 #     - "traefik.http.routers.loki.tls=true"
 #     - "traefik.http.routers.loki.tls.certresolver=cloudflare"
 #     - "traefik.http.routers.loki.service=loki"
 #     - "traefik.http.routers.loki.middlewares=local-only@file,authentik@file,security-headers@file"
 #     - "traefik.http.services.loki.loadbalancer.server.port=3100"

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    hostname: alloy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - ./alloy_data:/var/lib/alloy/data
      - /:/rootfs:ro
      - /run:/run:ro
      - /var/log:/var/log:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker/:ro
      - /run/udev/data:/run/udev/data:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - monitoring
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alloy.entrypoints=websecure"
      - "traefik.http.routers.alloy.rule=Host(`alloy.${DOMAIN_NAME}`)"
      - "traefik.http.routers.alloy.tls=true"
      - "traefik.http.routers.alloy.tls.certresolver=cloudflare"
      - "traefik.http.routers.alloy.service=alloy"
      - "traefik.http.routers.alloy.middlewares=local-only@file,authentik@file,security-headers@file"
      - "traefik.http.services.alloy.loadbalancer.server.port=12345"
 #
 # prometheus:
 #   image: prom/prometheus:latest
 #   container_name: prometheus
 #   restart: unless-stopped
 #   user: "65534:65534"
 #   security_opt:
 #     - no-new-privileges:true
 #   networks:
 #     - grafana-monitoring
 #   volumes:
 #     - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
 #     - ./prometheus_data:/prometheus
 #   command:
 #     - '--config.file=/etc/prometheus/prometheus.yml'
 #     - '--storage.tsdb.path=/prometheus'
 #     - '--web.console.libraries=/etc/prometheus/console_libraries'
 #     - '--web.console.templates=/etc/prometheus/consoles'
 #     - '--web.enable-lifecycle'
 #     - '--web.enable-admin-api'
 #     - '--storage.tsdb.retention.time=90d'
 #   labels:
 #     - "traefik.enable=true"
 #     - "traefik.http.routers.prometheus.entrypoints=websecure"
 #     - "traefik.http.routers.prometheus.rule=Host(`prometheus.${DOMAIN_NAME}`)"
 #     - "traefik.http.routers.prometheus.tls=true"
 #     - "traefik.http.routers.prometheus.tls.certresolver=cloudflare"
 #     - "traefik.http.routers.prometheus.service=prometheus"
 #     - "traefik.http.routers.prometheus.middlewares=local-only@file,authentik@file,security-headers@file"
 #     - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
#volumes:
#  alloy_data:
#    driver: local
#
networks:
  monitoring:
    name: monitoring
    external: true
  homelab:
    name: homelab
    external: true
