services:
  postgres:
    image: postgres:17-alpine
    container_name: personal-pg
    restart: unless-stopped
    networks:
      - pg
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C

  postgres-17:
    image: postgres:17-alpine
    container_name: postgres-17
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_17_PASSWORD}
    volumes:
      - /opt/postgres/pg17/data/:/var/lib/postgresql/data
    networks:
      - pg
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  pg:
    name: pg
